name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use a Linux runner for testing

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Use Python 3.8 (adjust if needed)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # You can add your test script here
        echo "Run tests if needed"

    - name: Deploy to server (optional)
      run: |
        # Your deployment commands go here (if you're deploying directly from GitHub)
        echo "Add deployment logic"
